name: React Project
# on: [push, workflow_dispatch]
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout the code
      uses: actions/checkout@v3.5.2

    - name: NodeJS Install
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install the dependencies
      run: npm ci

    - name: Run the test cases
      run: npm test
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout the code
      uses: actions/checkout@v3.5.2

    - name: NodeJS Install
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install the dependencies
      run: npm ci
    
    - name: Build the project
      run: npm run build
    
    - name: deploy
      run: echo "Deploying the react Git Applicaiton"


