name: ET
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.5.2
      - name: NodeJS Install
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install the dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run the test cases
        run: npm run test
      - name: deploy
        run: echo "Deploying the react Git Applicaiton"
